# tasks to complete before running roles
- hosts: all
  become: true
  tags: always
  pre_tasks:
    - name: Sample pre-role task
      debug:
        msg: Pre role task executed

# run roles
- hosts: all
  # tags: base
  become: true
  roles:
    - base

- hosts: edge
  become: true
  roles:
    - edge

# end of run cleanup and reporting
- hosts: all
  become: true
  tasks:
    - name: Run test Playbook
      include_tasks: playbooks/test.yml
      tags: always
