# tasks to complete before running roles
- hosts: all
  become: true
  tags: always
  pre_tasks:
    - name: Set Ansible-Pull to run in crond
      cron:
        name: "Run Ansible-Pull"
        minute: "*/15"
        job: "/usr/bin/ansible-pull -U https://github.com/josandersms/edge-ansible.git -C main"
        run_once: true
    - name: Sample pre-role task
      debug:
        msg: Pre role task executed

# run roles
- hosts: nuc
  become: true
  roles:
    - nuc
  run_once: true
- hosts: all
  # tags: base
  become: true
  roles:
    - base

- hosts: edge
  become: true
  roles:
    - edge

# end of run cleanup and reporting
- hosts: all
  become: true
  tasks:
    - name: Run test Playbook
      include_tasks: playbooks/test.yml
      tags: always
