- name: Copy .bashrc
  ansible.builtin.copy:
    src: files/misc/.bashrc
    dest: "/home/{{ admin_username }}/.bashrc"
    owner: "{{ admin_username }}"
    group: "{{ admin_username }}"
    mode: '0644'
