- name: install k3s
  ansible.builtin.script: ../files/scripts/install-k3s.sh
- name: set kubeconfig
  environment:
    ADMIN_USERNAME: "{{ admin_username }}"
  ansible.builtin.script: ../files/scripts/kubeconfig.sh
