- name: Get Variables
  ansible.builtin.include_vars: vars/all.yml
- name: Install k3s
  ansible.builtin.script: files/scripts/install-k3s.sh
- name: Set kubeconfig
  environment:
    ADMIN_USERNAME: "{{ admin_username }}"
  ansible.builtin.script: files/scripts/kubeconfig.sh
- name: Sysctl updates
  ansible.builtin.script: files/scripts/performance.sh
- name: Install Azure CLI
  ansible.builtin.script: files/scripts/install-azure-cli.sh
