- name: system setup | scripts | copy image_prep.sh script
  tags: scripts
  copy:
    src: scripts/install-k3s.sh
    dest: /usr/local/bin/install-k3s.sh
    owner: root
    group: root
    mode: 0755